name: Android Publisher CI

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode Google Services
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_SERVICES_PASSWORD }}" --output app/google-services.json app/google-services.json.gpg

      - name: Decode Signature
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SIGNATURE_PASSWORD }}" --output sign.jks sign.jks.gpg

      - name: Decode Publishing Secrets
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PLAY_PUBLISHER_PASSWORD }}" --output play_publisher.json play_publisher.json.gpg

      - name: Dependencies
        run: ./gradlew dependencies

      - name: Publish Release App
        run: ./gradlew publishReleaseBundle
        env:
          APP_KEYSTORE_ALIAS: ${{ secrets.APP_KEYSTORE_ALIAS }}
          APP_KEYSTORE_PASSWORD: ${{ secrets.APP_KEYSTORE_PASSWORD }}
          APP_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.APP_KEYSTORE_PRIVATE_KEY_PASSWORD }}

      - name: Upload result for job
        uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab
